#:schema node_modules/wrangler/config-schema.json
name = "transfordev-web"
compatibility_date = "2024-05-24"
pages_build_output_dir = "./build/client"

[[services]]
binding = "WORKER"
service = "transfordev-worker"
