#:schema node_modules/wrangler/config-schema.json
name = "transfordev-worker"
main = "app/main.ts"
compatibility_date = "2024-05-24"
workers_dev = false

[ai]
binding = "AI"

[[durable_objects.bindings]]
name = "TRANSLATION"
class_name = "DurableObjectTranslation"

[[migrations]]
tag = "v1"
new_classes = ["DurableObjectTranslation"]


[[kv_namespaces]]
binding = "LIST"
id = "818a290d586942da8bf50c046d9b2544"


[[queues.producers]]
binding = "QUEUE"
queue = "queue-transfordev"


[[queues.consumers]]
queue = "queue-transfordev"
# Optional: Configure batching and retries: https://developers.cloudflare.com/queues/learning/batching-retries/
# max_batch_size = 10
# max_batch_timeout = 30
# max_retries = 10
# dead_letter_queue = "my-queue-dlq"
